language: ruby
env:
  matrix:
  - RACK_ENV=development
sudo: false
rvm:
- 2.6.3
services:
  - docker
before_install:
- ./bin/pull_worker.sh
deploy:
  provider: rubygems
  api_key:
    secure: zh7xmw7n78ecpnFMn/zRrGDuLJm4SuBID9ETpEEmZyrQJVVfOr54UwVIdnOI71C6+PAGvdi8iuEy+nxiQOkzWvzWjM+DxSPZ+jn8b6mA7RsN81EpJ9wqnyrX2waMTbNnj8bGKz/OL3fFmaRVg/FSP1IDz2gZGU5LzgOt54CdrKRyPCvw6lM/oSgt1NFc9OFnsviNNXbH2d8PAuXu7SxTjedoXJNBgpfrpj4J5OdgIC6Pu5XD4KjZTS6n81KB9vwrOYcgBpMHrKWvuBuYh0UaCSUK+PXsMTkpzbFYbrvB9qqyBaZTjsVDJ0+BAv2BkOK8GxIA4nqyHncoSBz8TLISvRTJjbXTfpXz+f/hZoovDrBO3cLJAh/XW1160pHbKIbS45ZWYHHQrG3+A2HnK3US1kgaEy2X3+5gUSrwLsRLWx93PzdGgLnVohF3i6duFWeCYDY6IiH901/d4w0DcjVaFbfTvcBLSOtZ6kkcEdGGRE+cUKyaIlM5DQjacPgcmZJhP7IixLDGlaPNDUwl/WRp4oO0Mzo26id/+c+BYvx4GaAlA2tfD/1r9trv0BJpIx/VWFd8xF33nnisVx6+pWnPbV7+nv0fsNshpAXudZzKn8mEgztP+bbBFihr60k4kZkuNHNrnaTT9SBE+sRb1C7QexmlF6PmDhC+JrKsQ9IBB1g=
  gem: mumuki-html-runner
  on:
    tags: true
    repo: mumuki/mumuki-html-runner
